# Generated by Django 4.1.3 on 2022-11-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='texto_eleccion',
            field=models.IntegerField(choices=[(1, 'Muy Malo'), (2, 'Malo'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], max_length=1),
        ),
    ]
